var GAME_LEVELS = [
  ["                                                                                ",
   "                                                            x                   ",
   "                                                                                ",
   "                                                                         o      ",
   "                                                                           y    ",
   "                                                                        xxxx    ",
   "                                                                  xxx           ",
   "                                                   xx      xx    xx!xx          ",
   "                  o o o o o         o o      xx                  x!!!x          ",
   "                                                                 xx!xx          ",
   "                 xxxxxxxxxxxx      xxxxx                          xvx           ",
   "                                                                            xx  ",
   "  xx                                      oxo                                x  ",
   "  x                    o  o                                                  x  ",
   "  x                                      xxxxx                    o o      o x  ",
   "  x          xxxx                                                            x  ",
   "  x  @       x  x                     y          y               xxxxx       x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxx   xxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              x   x     x!!!x        x     x                    ",
   "                              x!!!x     x!!!x        x!!!!!x                    ",
   "                              x!!!x     x!!!x        x!!!!!x                    ",
   "                              xxxxx     xxxxx        xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                             x!x  ",
   "                                                                                                             x!x  ",
   "                                                                                                             x!x  ",
   "           o  o  o  o  o  o  o  o  o  o  o  o  o                                                             x!x  ",
   "                                                        o o                                       o   o   o  x!x  ",
   "        x xx xx xx xx xx xx xx xx xx xx xx xx xxxx x                                                        xx!x  ",
   "        x!xx!xx!xx!xx!xx!xx!xx!xx!xx!xx!xx!xx!xxxx!x   xxxxx         o o o o           xx     xxxxxxxxxxxxxxx!!x  ",
   "        xvxxvxxvxxvxxvxxvxxvxxvxxvxxvxxvxxvxxvxxxxvx         xx                  xx             !!!!!!!!!!!!!!xx  ",
   "                                                                    xxxxxxxxxx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                                               x         v                        ",
   "                                                                                                                  ",
   "                                                                                 xxx         xxx                  ",
   "                                               x     x                           x x  xx     x x                  ",
   "                                               x    xx                             x         x                    ",
   "                                               x     x                             xx      xxx                    ",
   "                                          xx   xx    x                             x         x                    ",
   "                                               x     x      o  o     x   x         x    x    x                    ",
   "               xxxxxxx        xxx   xxx        x    xx               x   x         x         x                    ",
   "              xx     xx         x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xx       xx        x o x          xx    x               x   x   x               x                    ",
   "     @       x         x        x   x          x     x               x   x   x               x                    ",
   "    xxx      x         x        x   x          x    xx               x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx o xx         x     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["x                  v           v   x",
   "xx                                 x",
   "xxx    o                           x",
   "xxxx y             o               x",
   "xxxxxxxxxxx           y       o    x",
   "      v           xxxxx          y x",
   "                  v          xxxxxxx",
   "                                   x",
   "                                   x",
   "                    xxxxx          x",
   "             o                     x",
   "                                   x",
   "           xxxxx                   x",
   "xx                                 x",
   "!|                      xxx     o  x",
   "xxxxxxxxxxxxxxxxxxx                x",
   "                               xxxxx",
   "               |       y       |!!!x",
   "       xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "               o                v  x",
   "               |        y          x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx      x",
   "         x        x      x       o x",
   "                    |              x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
